name: TrollReverseLab
options:
  bundleIdPrefix: com.trollreverse
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
    DEVELOPMENT_TEAM: ""
    PRODUCT_NAME: "$(TARGET_NAME)"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "14.0"
    TARGETED_DEVICE_FAMILY: "1"
    ARCHS: arm64
    ONLY_ACTIVE_ARCH: NO
    ENABLE_BITCODE: NO

targets:
  TrollReverseLab:
    type: application
    platform: iOS
    sources:
      - path: TrollReverseLab
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: TrollReverseLab/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: TrollReverseLab/TrollReverseLab.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.trollreverse.reverselab
        MARKETING_VERSION: "6.3.15"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(PROJECT_DIR)/TrollReverseLab/Frameworks"
        OTHER_LDFLAGS: "-ObjC -lsqlite3"
    entitlements:
      path: TrollReverseLab/TrollReverseLab.entitlements
    info:
      path: TrollReverseLab/Resources/Info.plist
